---
swagger: "2.0"
info:
  version: "1.0"
  title: "Hello World API"
schemes:
- "https"
- "http"
paths:
  /Hello/{user}:
    get:
      summary: "Returns a hello world to a user"
      description: "Returns a hello world to a user"
      operationId: "getUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "user"
        in: "path"
        description: "The name of the user to greet."
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      x-swagger-router-controller: "Default"
definitions:
  User:
    type: "object"
    properties:
      username:
        type: "string"
        description: "The user name."
    example:
      username: "username"
